### ISSUE TITLE
Discord.js v13

### ISSUE THREAD

**Issue by Lcxd65** [dionsyran2/hangman-discord#1]
Hello! I LOVE your package. Can you plaese uodate it so I can use it with discordjs v13 🥰

**Comment by dionsyran2** [comment]
Sure, i was updating my other bots and i completely forgot about this one, i will let you know when its done

**Comment by Lcxd65** [comment]
okay thanks a lot 🥰

**Comment by dionsyran2** [comment]
Hello, 
I just finished upgrading my package, you can upgrade by running `npm i hangman-discord@latest`, but please read the documentation again, as most of the events have been changed.
Sincerely,
dionsyran2
